on:
  pull_request:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

name: Dev Branch Pull Request
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: testing
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RG_NAME }}
          template: main.bicep
          parameters: parameters.bicepparam
          deploymentMode: Validate
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.RG_NAME }}
          template: main.bicep
          parameters: parameters.bicepparam
          deploymentMode: Incremental
          failOnStandardError: false
          failOnStdErr: false